### ISSUE TITLE
Load values based on a condition

### ISSUE THREAD

**Issue by wonderiuy** [gerritvankuipers/aspjson#1]
Hello Gerrit,
thank you for your incredible and useful work. I'm asking if it's possible to load JSON values based on a condition of a field (ie: a date)
Thank you in advance
Best regards

**Comment by gerritvankuipers** [comment]
Hi, I’m not sure what you mean. Do you mean load json content, then filter the items within the json document based on a date field? If this is what you want, then no, the class does not have a filter function. If you mean something else, can you please provide an example?
Extra challenge using dates is the fact that JSON does not have a built-in type for date/time values.

**Comment by wonderiuy** [comment]
Thank you for your answer. I mean exactly a filter function, after or concurrent to data loading. This is for avoiding cycling all the records and get only the filtered one.
Ther best would be to load only the desired data, based on a filter

**Comment by gerritvankuipers** [comment]
Hi, the class has no support for that.
The preferred approach would be to put a filter in the api request to get just the records you need. But if that’s not an option, I guess you just have to loop and skip all the irrelevant items.

**Comment by wonderiuy** [comment]
Thank you, will loop and skip, as i'm already doing.
Best regards
